formate yml

diff --git a/.github/workflows/prod-deploy.yml b/.github/workflows/prod-deploy.yml
--- a/.github/workflows/prod-deploy.yml
+++ b/.github/workflows/prod-deploy.yml
@@ -19,80 +19,88 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-          - name: Build the backed docker image
-            run:  docker build -t rahuldocker974/backend_beatroom:${{github.sha}} ./backend 
+      - name: Build the backend docker image
+        run: docker build -t rahuldocker974/backend_beatroom:${{ github.sha }} ./backend
 
-          - name: Push to backend docker image
-            run: docker push rahuldocker974/backend_beatroom:${{github.sha}} 
+      - name: Push backend docker image
+        run: docker push rahuldocker974/backend_beatroom:${{ github.sha }}
 
-          - name: Build the frontend docker image
-            run: docker build -t --build-ags NEXT_PUBLIC_BASE_URL=${{secretsNEXT_PUBLIC_BASE_URL}} rahuldocker974/frontend_beatroom:${{github.sha}} ./frontend
+      - name: Build the frontend docker image
+        run: |
+          docker build \
+            --build-arg NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} \
+            -t rahuldocker974/frontend_beatroom:${{ github.sha }} \
+            ./frontend
 
-          - name: Push to frontend docker image
-            run: docker push rahuldocker974/frontend_beatroom:${{github.sha}}
+      - name: Push frontend docker image
+        run: docker push rahuldocker974/frontend_beatroom:${{ github.sha }}
 
-          - name: ssh into backend VM and start the docker container
-            uses:applyboy/ssh-action@v1
-            with:
-               host: ${{ secrets.HOST }}
-               username: ${{ secrets.USERNAME }}
-               key: ${{ secrets.KEY }}
-               port: ${{ secrets.PORT }}
-               script: |
-                 if ! command -v docker &> /dev/null
-                 then
-                   echo "Docker not found. Installing..."
-                   apt update
-                   apt install -y docker.io
-                   systemctl start docker
-                   systemctl enable docker
-                 else
-                   echo "Docker already installed. Skipping installation."
-                 fi
-                 echo "NODE_ENV=${{secrets.NODE_ENV}}" >> .env
-                 echo "CROSS_ORIGIN_URL=${{secrets.CROSS_ORIGIN_URL}}" >> .env
-                 echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
-                 echo "PORT=${{secrets.PORT_BACKEND}}" >> .env
-                 echo "OTP_SECRET=${{secrets.OTP_SECRET}}" >> .env
-                 echo "Ac_SECRET=${{secrets.Ac_SECRET}}" >> .env
-                 echo "Ref_SECRET=${{secrets.Ref_SECRET}}" >> .env
-                 echo "UINQUE_USERID_SECRET=${{secrets.UINQUE_USERID_SECRET}}" >> .env
-                 echo "EMAIL=${{secrets.EMAIL}}" >> .env
-                 echo "EMAIL_PASS=${{secrets.EMAIL_PASS}}" >> .env
-                 docker pull rahuldocker974/backend_beatroom:${{ github.sha }}
-                 docker stop backend || true
-                 docker rm backend || true
-                   docker run -d \
-                     -p 8080:8080 \
-                     --name backend  \
-                     --env-file .env \
-                     --restart unless-stopped \
-                     rahuldocker974/backend_beatroom:${{github.sha}}
-      
-            - name: ssh into frontend VM and start the docker container
-              uses: applyboy/ssh-action@v1
-              with:
-                host:${{secrets.HOST_FRONTEND}}
-                username:${{secrets.USERNAME_FRONTEND}}
-                key:${{secrets.KEY_FRONTEND}}
-                port:${{secrets.PORT_FRONTEND}}
-                script: |
-                    if ! command -v docker &> /dev/null
-                    then
-                      echo "Docker not found. Installing..."
-                      apt update
-                      apt install -y docker.io
-                      systemctl start docker
-                      systemctl enable docker
-                    else
-                      echo "Docker already installed. Skipping installation."
-                    fi
-                    docker pull rahuldocker974/frontend_beatroom:${{github.sha}}
-                    docker stop frontend || true
-                    docker rm frontend || true
-                    docker run -d \
-                      -p 3000:3000 \
-                      --name frontend  \
-                      --restart unless-stopped \ 
-                      rahuldocker974/frontend_beatroom:${{github.sha}}
-                  
+      - name: SSH into backend VM and start Docker container
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.KEY }}
+          port: ${{ secrets.PORT }}
+          script: |
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing..."
+              sudo apt update
+              sudo apt install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            else
+              echo "Docker already installed. Skipping installation."
+            fi
+
+            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
+            echo "CROSS_ORIGIN_URL=${{ secrets.CROSS_ORIGIN_URL }}" >> .env
+            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
+            echo "PORT=${{ secrets.PORT_BACKEND }}" >> .env
+            echo "OTP_SECRET=${{ secrets.OTP_SECRET }}" >> .env
+            echo "Ac_SECRET=${{ secrets.Ac_SECRET }}" >> .env
+            echo "Ref_SECRET=${{ secrets.Ref_SECRET }}" >> .env
+            echo "UINQUE_USERID_SECRET=${{ secrets.UINQUE_USERID_SECRET }}" >> .env
+            echo "EMAIL=${{ secrets.EMAIL }}" >> .env
+            echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
+
+            docker pull rahuldocker974/backend_beatroom:${{ github.sha }}
+            docker stop backend || true
+            docker rm backend || true
+
+            docker run -d \
+              -p 8080:8080 \
+              --name backend \
+              --env-file .env \
+              --restart unless-stopped \
+              rahuldocker974/backend_beatroom:${{ github.sha }}
+
+      - name: SSH into frontend VM and start Docker container
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.HOST_FRONTEND }}
+          username: ${{ secrets.USERNAME_FRONTEND }}
+          key: ${{ secrets.KEY_FRONTEND }}
+          port: ${{ secrets.PORT_FRONTEND }}
+          script: |
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing..."
+              sudo apt update
+              sudo apt install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            else
+              echo "Docker already installed. Skipping installation."
+            fi
+
+            docker pull rahuldocker974/frontend_beatroom:${{ github.sha }}
+            docker stop frontend || true
+            docker rm frontend || true
+
+            docker run -d \
+              -p 3000:3000 \
+              --name frontend \
+              --restart unless-stopped \
+              rahuldocker974/frontend_beatroom:${{ github.sha }}
