fix

diff --git a/.github/workflows/prod-deploy.yml b/.github/workflows/prod-deploy.yml
--- a/.github/workflows/prod-deploy.yml
+++ b/.github/workflows/prod-deploy.yml
@@ -33,6 +33,16 @@ jobs:
           key: ${{ secrets.KEY }}
           port: ${{ secrets.PORT }}
           script: |
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing..."
+              apt update
+              apt install -y docker.io
+              systemctl start docker
+              systemctl enable docker
+            else
+              echo "Docker already installed. Skipping installation."
+            fi
             echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
             echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
             echo "PORT=${{ secrets.PORT_BACKEND }}" >> .env
